### ISSUE TITLE
AsyncObject#fetchFromEndpoint using POST

### ISSUE THREAD

**Issue by glesperance** [glesperance/chocobo#4]
Hey Guys,

I was wondering if there were any reason why the `AsyncObject#fetchFromEndpoint` is using `POST` HTTP method ?

Is it an artifact of a previous iteration of the code? It seems it is never called...

Thanks!

Gabriel

**Comment by markhazlett** [comment]
Hey Gabriel,

You caught us at a great time. We are just fixing that right now. It was an previous iteration and we named it terribly. @LGrizz is about to commit a fix for that now.

**Comment by glesperance** [comment]
@markhazlett awesome!
Thanks for the quick answer!

I was looking for a backbone like library to manage my models /collection for a new iOS app I'm developing; seems indeed like I found you guys at a great time!

Looking forward to use your lib :)

Gabriel

**Comment by markhazlett** [comment]
Actually, I was just re-reading your question. The reason that `fetchFromEndpoint` is never called is that the collection and model extend from AsyncObject and therefore can use the fetchFromEndpoint call at anytime. We just changed the name of fetchFromEndpoint to postToEndpoint instead so it's a little clearer. This allows you to post to an endpoint from a model.

**Comment by glesperance** [comment]
I was wondering about the weird naming as well as the possibility to issue PUT / POST updates to the endpoint as well. 

Pull request #5 definitely resolved most of the issues I had with the lib.

I'll definitely pull the repo and give it a try today.

**Comment by markhazlett** [comment]
Awesome, let us know if there's any issues.
