### ISSUE TITLE
Issues compiling the pod (with latest repo code)

### ISSUE THREAD

**Issue by glesperance** [glesperance/chocobo#6]
Hey Guys,

I'm getting the following error when I try to compile the pod within my project : 

```
MyProject/Pods/Chocobo/Classes/ios/AsyncObject.m:27:86: No visible @interface for 'AsyncObject' declares the selector 'updateParams:'
```

Any idea what might be causing this?

Thank you.

Gabriel

**Comment by LGrizz** [comment]
Hey Gabriel,

We had been using the pod in another project and this was a bit of legacy code that got ported over. We're putting some tests in place to catch this sort of issue going forward.

Cheers,

Kyle

**Comment by glesperance** [comment]
Awesome ; it's working now. Thanks for the quick turnaround !
